#!/bin/bash
DBT5NAME="dbt5"

# Clause 2.2.5.1
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE account_permission
" &>/dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE account_permission (
    ap_ca_id BIGINT NOT NULL,
    ap_acl VARCHAR(4) NOT NULL,
    ap_tax_id VARCHAR(20) NOT NULL,
    ap_l_name VARCHAR(30) NOT NULL,
    ap_f_name VARCHAR(30) NOT NULL,
    PRIMARY KEY( ap_ca_id, ap_tax_id ) )
    ;
" || exit 1	

# Clause 2.2.5.2
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE customer
" &>/dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE customer (
    c_id BIGINT NOT NULL,
    c_tax_id VARCHAR(20) NOT NULL,
    c_st_id VARCHAR(4) NOT NULL,
    c_l_name VARCHAR(30) NOT NULL,
    c_f_name VARCHAR(30) NOT NULL,
    c_m_name CHAR(1),
    c_gndr CHAR(1),
    c_tier SMALLINT NOT NULL,
    c_dob DATE NOT NULL,
    c_ad_id BIGINT NOT NULL,
    c_ctry_1 VARCHAR(3),
    c_area_1 VARCHAR(3),
    c_local_1 VARCHAR(10),
    c_ext_1 VARCHAR(5),
    c_ctry_2 VARCHAR(3),
    c_area_2 VARCHAR(3),
    c_local_2 VARCHAR(10),
    c_ext_2 VARCHAR(5),
    c_ctry_3 VARCHAR(3),
    c_area_3 VARCHAR(3),
    c_local_3 VARCHAR(10),
    c_ext_3 VARCHAR(5),
    c_email_1 VARCHAR(50),
    c_email_2 VARCHAR(50),
    PRIMARY KEY (c_id) )
    ;
" || exit 1

# Clause 2.2.5.3
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE customer_account
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE customer_account (
    ca_id BIGINT NOT NULL,
    ca_b_id BIGINT NOT NULL,
    ca_c_id BIGINT NOT NULL,
    ca_name VARCHAR(50),
    ca_tax_st SMALLINT NOT NULL,
    ca_bal NUMERIC(12,2) NOT NULL,
    PRIMARY KEY(ca_id) )
    ;
" || exit 1

# Clause 2.2.5.4
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE customer_taxrate
" &> /dev/null
mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE customer_taxrate (
    cx_tx_id VARCHAR(4) NOT NULL,
    cx_c_id BIGINT NOT NULL,
    PRIMARY KEY(cx_tx_id, cx_c_id) )
    ;
" || exit 1

# Clause 2.2.5.5
mysql -u root ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE holding
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE holding (
    h_t_id BIGINT NOT NULL,
    h_ca_id BIGINT NOT NULL,
    h_s_symb VARCHAR(15) NOT NULL,
    h_dts TIMESTAMP NOT NULL,
    h_price NUMERIC(8,2) NOT NULL,
    h_qty INTEGER NOT NULL,
    PRIMARY KEY(h_t_id) )
    ;
" || exit 1

# Clause 2.2.5.6
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE holding_history
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE holding_history (
    hh_h_t_id BIGINT NOT NULL,
    hh_t_id BIGINT NOT NULL,
    hh_before_qty INTEGER NOT NULL,
    hh_after_qty INTEGER NOT NULL,
    PRIMARY KEY(hh_h_t_id, hh_t_id) )
    ;
" || exit 1

# Clause 2.2.5.7
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE holding_summary
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE holding_summary (
    hs_ca_id BIGINT NOT NULL,
    hs_s_symb VARCHAR(15) NOT NULL,
    hs_qty INTEGER NOT NULL,
    PRIMARY KEY( hs_ca_id, hs_s_symb) )
    ;
" || exit 1

# Clause 2.2.5.8
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE watch_item
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE watch_item (
    wi_wl_id BIGINT NOT NULL,
    wi_s_symb VARCHAR(15) NOT NULL,
    PRIMARY KEY(wi_wl_id, wi_s_symb) )
    ;
" || exit 1

# Clause 2.2.5.9
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE watch_list
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE watch_list (
    wl_id BIGINT NOT NULL,
    wl_c_id BIGINT NOT NULL,
    PRIMARY KEY (wl_id) )
    ;
" || exit 1

# Broker Tables

# Clause 2.2.6.1
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE broker
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE broker (
    b_id BIGINT NOT NULL,
    b_st_id VARCHAR(4) NOT NULL,
    b_name VARCHAR(100) NOT NULL,
    b_num_trades INTEGER NOT NULL,
    b_comm_total NUMERIC(12,2) NOT NULL,
    PRIMARY KEY(b_id) )
    ;
" || exit 1

# Clause 2.2.6.2
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE cash_transaction
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE cash_transaction (
    ct_t_id BIGINT NOT NULL,
    ct_dts TIMESTAMP NOT NULL,
    ct_amt NUMERIC(10,2) NOT NULL,
    ct_name VARCHAR(100),
    PRIMARY KEY (ct_t_id))
    ;
" || exit 1

# Clause 2.2.6.3
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE charge
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE charge (
    ch_tt_id VARCHAR(3) NOT NULL,
    ch_c_tier SMALLINT,
    ch_chrg NUMERIC(10,2),
    PRIMARY KEY (ch_tt_id, ch_c_tier))
    ;
" || exit 1

# Clause 2.2.6.4
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE commission_rate
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE commission_rate (
    cr_c_tier SMALLINT NOT NULL,
    cr_tt_id VARCHAR(3) NOT NULL,
    cr_ex_id VARCHAR(6) NOT NULL,
    cr_from_qty INTEGER NOT NULL,
    cr_to_qty INTEGER NOT NULL,
    cr_rate NUMERIC(5, 2) NOT NULL, 
    PRIMARY KEY (cr_c_tier, cr_tt_id, cr_ex_id, cr_from_qty))
    ;
" || exit 1

# Clause 2.2.6.5
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE settlement
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE settlement (
    se_t_id BIGINT NOT NULL,
    se_cash_type VARCHAR(40) NOT NULL,
    se_cash_due_date DATE NOT NULL,
    se_amt NUMERIC(10,2) NOT NULL,
    PRIMARY KEY (se_t_id))
    ;
" || exit 1

# Clause 2.2.6.6
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE trade
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE trade (
    t_id BIGINT NOT NULL AUTO_INCREMENT,
    t_dts TIMESTAMP NOT NULL,
    t_st_id VARCHAR(4) NOT NULL,
    t_tt_id VARCHAR(3) NOT NULL,
    t_is_cash BOOLEAN NOT NULL,
    t_s_symb VARCHAR(15) NOT NULL,
    t_qty INTEGER NOT NULL,
    t_bid_price NUMERIC(8,2) NOT NULL,
    t_ca_id BIGINT NOT NULL,
    t_exec_name VARCHAR(64) NOT NULL,
    t_trade_price NUMERIC(8,2),
    t_chrg NUMERIC(10,2) NOT NULL,
    t_comm NUMERIC(10,2) NOT NULL,
    t_tax NUMERIC(10,2) NOT NULL,
    t_lifo BOOLEAN NOT NULL,
    PRIMARY KEY( t_id ) )
    ;
" || exit 1

# Clause 2.2.6.7
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE trade_history
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE trade_history (
    th_t_id BIGINT NOT NULL,
    th_dts TIMESTAMP NOT NULL,
    th_st_id VARCHAR(4) NOT NULL,
    PRIMARY KEY (th_t_id, th_st_id))
    ;
" || exit 1

# Clause 2.2.6.8
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE trade_request
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE trade_request (
    tr_t_id BIGINT NOT NULL,
    tr_tt_id VARCHAR(3) NOT NULL,
    tr_s_symb VARCHAR(15) NOT NULL,
    tr_qty INTEGER NOT NULL,
    tr_bid_price NUMERIC(8,2) NOT NULL,
    tr_b_id BIGINT NOT NULL,
    PRIMARY KEY (tr_t_id))
    ;
" || exit 1

# Clause 2.2.6.9
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE trade_type
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE trade_type (
    tt_id VARCHAR(3) NOT NULL,
    tt_name VARCHAR(12) NOT NULL,
    tt_is_sell BOOLEAN NOT NULL,
    tt_is_mrkt BOOLEAN NOT NULL,
    PRIMARY KEY (tt_id))
    ;
" || exit 1

# Market Tables

# Clause 2.2.7.1
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE company
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE company (
    co_id BIGINT NOT NULL,
    co_st_id VARCHAR(4) NOT NULL,
    co_name VARCHAR(60) NOT NULL,
    co_in_id VARCHAR(2) NOT NULL,
    co_sp_rate VARCHAR(4) NOT NULL,
    co_ceo VARCHAR(100) NOT NULL,
    co_ad_id BIGINT NOT NULL,
    co_desc VARCHAR(150) NOT NULL,
    co_open_date DATE NOT NULL,
    PRIMARY KEY (co_id))
    ;
" || exit 1

# Clause 2.2.7.2
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE company_competitor
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE company_competitor (
    cp_co_id BIGINT NOT NULL,
    cp_comp_co_id BIGINT NOT NULL,
    cp_in_id VARCHAR(2) NOT NULL,
    PRIMARY KEY (cp_co_id, cp_comp_co_id, cp_in_id))
    ;
" || exit 1

# Clause 2.2.7.3
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE daily_market
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE daily_market (
    dm_date DATE NOT NULL,
    dm_s_symb VARCHAR(15) NOT NULL,
    dm_close NUMERIC(8,2) NOT NULL,
    dm_high NUMERIC(8,2) NOT NULL,
    dm_low NUMERIC(8,2) NOT NULL,
    dm_vol BIGINT NOT NULL,
    PRIMARY KEY (dm_date, dm_s_symb))
    ;
" || exit 1

# Clause 2.2.7.4
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE exchange
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE exchange (
    ex_id VARCHAR(6) NOT NULL,
    ex_name VARCHAR(100) NOT NULL,
    ex_num_symb INTEGER NOT NULL,
    ex_open INTEGER NOT NULL,
    ex_close INTEGER NOT NULL,
    ex_desc VARCHAR(150),
    ex_ad_id BIGINT NOT NULL,
    PRIMARY KEY (ex_id))
    ;
" || exit 1

# Clause 2.2.7.5
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE financial
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE financial (
    fi_co_id BIGINT NOT NULL,
    fi_year INTEGER NOT NULL,
    fi_qtr SMALLINT NOT NULL,
    fi_qtr_start_date DATE NOT NULL,
    fi_revenue NUMERIC(15,2) NOT NULL,
    fi_net_earn NUMERIC(15,2) NOT NULL,
    fi_basic_eps NUMERIC(10,2) NOT NULL,
    fi_dilut_eps NUMERIC(10,2) NOT NULL,
    fi_margin NUMERIC(10,2) NOT NULL,
    fi_inventory NUMERIC(15,2) NOT NULL,
    fi_assets NUMERIC(15,2) NOT NULL,
    fi_liability NUMERIC(15,2) NOT NULL,
    fi_out_basic BIGINT NOT NULL,
    fi_out_dilut BIGINT NOT NULL,
    PRIMARY KEY (fi_co_id, fi_year, fi_qtr))
    ;
" || exit 1

# Clause 2.2.7.6
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE industry
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE industry (
    in_id VARCHAR(2) NOT NULL,
    in_name VARCHAR(50) NOT NULL,
    in_sc_id VARCHAR(2) NOT NULL,
    PRIMARY KEY (in_id))
    ;
" || exit 1

# Clause 2.2.7.7
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE last_trade
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE last_trade (
    lt_s_symb VARCHAR(15) NOT NULL,
    lt_dts TIMESTAMP NOT NULL,
    lt_price NUMERIC(8,2) NOT NULL,
    lt_open_price NUMERIC(8,2) NOT NULL,
    lt_vol BIGINT,
    PRIMARY KEY (lt_s_symb))
    ;
" || exit 1

# Clause 2.2.7.8
# FIXME: The NI_ITEM field may be either LOB(100000) or
#	LOB_Ref, which is a reference to a LOB(100000) object
#	stored outside the table. 
#	TEXT seems to be simpler to handle

mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE news_item
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE news_item (
    ni_id BIGINT NOT NULL,
    ni_headline VARCHAR(80) NOT NULL,
    ni_summary VARCHAR(255) NOT NULL,
    ni_item BLOB NOT NULL,
    ni_dts TIMESTAMP NOT NULL,
    ni_source VARCHAR(30) NOT NULL,
    ni_author VARCHAR(30),
    PRIMARY KEY (ni_id))
    ;
" || exit 1

# Clause 2.2.7.9
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE news_xref
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE news_xref (
    nx_ni_id BIGINT NOT NULL,
    nx_co_id BIGINT NOT NULL,
    PRIMARY KEY (nx_ni_id, nx_co_id))
    ;
" || exit 1

# Clause 2.2.7.10
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE sector
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE sector (
    sc_id VARCHAR(2) NOT NULL,
    sc_name VARCHAR(30) NOT NULL,
    PRIMARY KEY (sc_id))
    ;
" || exit 1

# Clause 2.2.7.11
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE security
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE security (
    s_symb VARCHAR(15) NOT NULL,
    s_issue VARCHAR(6) NOT NULL,
    s_st_id VARCHAR(4) NOT NULL,
    s_name VARCHAR(70) NOT NULL,
    s_ex_id VARCHAR(6) NOT NULL,
    s_co_id BIGINT NOT NULL,
    s_num_out BIGINT NOT NULL,
    s_start_date DATE NOT NULL,
    s_exch_date DATE NOT NULL,
    s_pe NUMERIC(10,2) NOT NULL,
    s_52wk_high NUMERIC(8,2) NOT NULL,
    s_52wk_high_date DATE NOT NULL,
    s_52wk_low NUMERIC(8,2) NOT NULL,
    s_52wk_low_date DATE NOT NULL,
    s_dividend NUMERIC(10,2) NOT NULL,
    s_yield NUMERIC(5,2) NOT NULL,
    PRIMARY KEY (s_symb))
    ;
" || exit 1

# Dimension Tables

# Clause 2.2.8.1
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE address
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE address (
    ad_id BIGINT NOT NULL,
    ad_line1 VARCHAR(80),
    ad_line2 VARCHAR(80),
    ad_zc_code VARCHAR(12) NOT NULL,
    ad_ctry VARCHAR(80),
    PRIMARY KEY (ad_id) )
    ;
" || exit 1

# Clause 2.2.8.2
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE status_type
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE status_type (
    st_id VARCHAR(4) NOT NULL,
    st_name VARCHAR(10) NOT NULL,
    PRIMARY KEY (st_id))
    ;
" || exit 1

# Clause 2.2.8.3
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE taxrate
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE taxrate (
    tx_id VARCHAR(4) NOT NULL,
    tx_name VARCHAR(50) NOT NULL,
    tx_rate NUMERIC(6,5) NOT NULL,
    PRIMARY KEY (tx_id))
    ;
" || exit 1

# Clause 2.2.8.4
mysql -u root -D ${DBT5NAME} -e "
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE zip_code
" &> /dev/null

mysql -u root -D ${DBT5NAME} -e "
CREATE TABLE zip_code (
    zc_code VARCHAR(12) NOT NULL,
    zc_town VARCHAR(80) NOT NULL,
    zc_div VARCHAR(80) NOT NULL,
    PRIMARY KEY (zc_code))
    ;
" || exit 1

# FKs
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE account_permission
ADD CONSTRAINT fk_account_permission_ca FOREIGN KEY (ap_ca_id) 
REFERENCES customer_account (ca_id);
" || exit 1

# Clause 2.2.5.2
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE customer
ADD CONSTRAINT fk_customer_st FOREIGN KEY (c_st_id) 
REFERENCES status_type (st_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE customer
ADD CONSTRAINT fk_customer_ad FOREIGN KEY (c_ad_id) 
REFERENCES address (ad_id);
" || exit 1

# Clause 2.2.5.3
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE customer_account
ADD CONSTRAINT fk_customer_account_b FOREIGN KEY (ca_b_id) 
REFERENCES broker (b_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE customer_account
ADD CONSTRAINT fk_customer_account_c FOREIGN KEY (ca_c_id) 
REFERENCES customer (c_id);
" || exit 1

# Clause 2.2.5.4
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE customer_taxrate
ADD CONSTRAINT fk_customer_taxrate_tx FOREIGN KEY (cx_tx_id) 
REFERENCES taxrate (tx_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE customer_taxrate
ADD CONSTRAINT fk_customer_taxrate_c FOREIGN KEY (cx_c_id) 
REFERENCES customer (c_id);
" || exit 1

# Clause 2.2.5.5
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE holding
ADD CONSTRAINT fk_holding_t FOREIGN KEY (h_t_id) 
REFERENCES trade (t_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE holding
ADD CONSTRAINT fk_holding_hs FOREIGN KEY (h_ca_id, h_s_symb) 
REFERENCES holding_summary (hs_ca_id, hs_s_symb);
" || exit 1

# Clause 2.2.5.6
# FIXME: Should the next two foreign keys be a single definition?
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE holding_history
ADD CONSTRAINT fk_holding_history_t1 FOREIGN KEY (hh_h_t_id) 
REFERENCES trade (t_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE holding_history
ADD CONSTRAINT fk_holding_history_t2 FOREIGN KEY (hh_t_id) 
REFERENCES trade (t_id);
" || exit 1

# Clause 2.2.5.7
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE holding_summary
ADD CONSTRAINT fk_holding_summary_ca FOREIGN KEY (hs_ca_id) 
REFERENCES customer_account (ca_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE holding_summary
ADD CONSTRAINT fk_holding_summary_s FOREIGN KEY (hs_s_symb) 
REFERENCES security (s_symb);
" || exit 1

# Clause 2.2.5.8
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE watch_item
ADD CONSTRAINT fk_watch_item_wl FOREIGN KEY (wi_wl_id) 
REFERENCES watch_list (wl_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE watch_item
ADD CONSTRAINT fk_watch_item_s FOREIGN KEY (wi_s_symb) 
REFERENCES security (s_symb);
" || exit 1

# Clause 2.2.5.9
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE watch_list
ADD CONSTRAINT fk_watch_list FOREIGN KEY (wl_c_id) 
REFERENCES customer (c_id);
" || exit 1

# Clause 2.2.6.1
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE broker
ADD CONSTRAINT fk_broker FOREIGN KEY (b_st_id) 
REFERENCES status_type (st_id);
" || exit 1

# Clause 2.2.6.2
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE cash_transaction
ADD CONSTRAINT fk_cash_transaction FOREIGN KEY (ct_t_id) 
REFERENCES trade (t_id);
" || exit 1

# Clause 2.2.6.3
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE charge
ADD CONSTRAINT fk_charge FOREIGN KEY (ch_tt_id) 
REFERENCES trade_type (tt_id);
" || exit 1

# Clause 2.2.6.4
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE commission_rate
ADD CONSTRAINT fk_commission_rate_tt FOREIGN KEY (cr_tt_id) 
REFERENCES trade_type (tt_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE commission_rate
ADD CONSTRAINT fk_commission_rate_ex FOREIGN KEY (cr_ex_id) 
REFERENCES exchange (ex_id);
" || exit 1

# Clause 2.2.6.5
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE settlement
ADD CONSTRAINT fk_settlement FOREIGN KEY (se_t_id) 
REFERENCES trade (t_id);
" || exit 1

# Clause 2.2.6.6
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE trade
ADD CONSTRAINT fk_trade_st FOREIGN KEY (t_st_id) 
REFERENCES status_type (st_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE trade
ADD CONSTRAINT fk_trade_tt FOREIGN KEY (t_tt_id) 
REFERENCES trade_type (tt_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE trade
ADD CONSTRAINT fk_trade_s FOREIGN KEY (t_s_symb) 
REFERENCES security (s_symb);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE trade
ADD CONSTRAINT fk_trade_ca FOREIGN KEY (t_ca_id) 
REFERENCES customer_account (ca_id);
" || exit 1

# Clause 2.2.6.7
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE trade_history
ADD CONSTRAINT fk_trade_history_t FOREIGN KEY (th_t_id) 
REFERENCES trade (t_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE trade_history
ADD CONSTRAINT fk_trade_history_st FOREIGN KEY (th_st_id) 
REFERENCES status_type (st_id);
" || exit 1

# Clause 2.2.6.8
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE trade_request
ADD CONSTRAINT fk_trade_request_t FOREIGN KEY (tr_t_id) 
REFERENCES trade (t_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE trade_request
ADD CONSTRAINT fk_trade_request_tt FOREIGN KEY (tr_tt_id) 
REFERENCES trade_type (tt_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE trade_request
ADD CONSTRAINT fk_trade_request_s FOREIGN KEY (tr_s_symb) 
REFERENCES security (s_symb);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE trade_request
ADD CONSTRAINT fk_trade_request_b FOREIGN KEY (tr_b_id) 
REFERENCES broker (b_id);
" || exit 1

# Clause 2.2.7.1
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE company
ADD CONSTRAINT fk_company_st FOREIGN KEY (co_st_id) 
REFERENCES status_type (st_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE company
ADD CONSTRAINT fk_company_in FOREIGN KEY (co_in_id) 
REFERENCES industry (in_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE company
ADD CONSTRAINT fk_company_ad FOREIGN KEY (co_ad_id) 
REFERENCES address (ad_id);
" || exit 1

# Clause 2.2.7.2
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE company_competitor
ADD CONSTRAINT fk_company_competitor_co FOREIGN KEY (cp_co_id) 
REFERENCES company (co_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE company_competitor
ADD CONSTRAINT fk_company_competitor_co2 FOREIGN KEY (cp_comp_co_id) 
REFERENCES company (co_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE company_competitor
ADD CONSTRAINT fk_company_competitor_in FOREIGN KEY (cp_in_id) 
REFERENCES industry (in_id);
" || exit 1

# Clause 2.2.7.3
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE daily_market
ADD CONSTRAINT fk_daily_market FOREIGN KEY (dm_s_symb) 
REFERENCES security (s_symb);
" || exit 1

# Clause 2.2.7.4
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE exchange
ADD CONSTRAINT fk_exchange FOREIGN KEY (ex_ad_id) 
REFERENCES address (ad_id);
" || exit 1

# Clause 2.2.7.5
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE financial
ADD CONSTRAINT fk_financial FOREIGN KEY (fi_co_id) 
REFERENCES company (co_id);
" || exit 1

# Clause 2.2.7.6
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE industry
ADD CONSTRAINT fk_industry FOREIGN KEY (in_sc_id) 
REFERENCES sector (sc_id);
" || exit 1

# Clause 2.2.7.7
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE last_trade
ADD CONSTRAINT fk_last_trade FOREIGN KEY (lt_s_symb) 
REFERENCES security (s_symb);
" || exit 1

# Clause 2.2.7.9
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE news_xref
ADD CONSTRAINT fk_news_xref_ni FOREIGN KEY (nx_ni_id) 
REFERENCES news_item (ni_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE news_xref
ADD CONSTRAINT fk_news_xref_co FOREIGN KEY (nx_co_id) 
REFERENCES company (co_id);
" || exit 1

# Clause 2.2.7.11
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE security
ADD CONSTRAINT fk_security_st FOREIGN KEY (s_st_id) 
REFERENCES status_type (st_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE security
ADD CONSTRAINT fk_security_ex FOREIGN KEY (s_ex_id) 
REFERENCES exchange (ex_id);
" || exit 1

mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE security
ADD CONSTRAINT fk_security_co FOREIGN KEY (s_co_id) 
REFERENCES company (co_id);
" || exit 1

# Clause 2.2.8.1
mysql -u root -D ${DBT5NAME} -e "
ALTER TABLE address
ADD CONSTRAINT fk_address FOREIGN KEY (ad_zc_code) 
REFERENCES zip_code (zc_code);
" || exit 1

# Add indexes

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_c_tax_id
ON customer (c_tax_id);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_ca_c_id
ON customer_account (ca_c_id);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_wl_c_id
ON watch_list (wl_c_id);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_dm_s_symb
ON daily_market (dm_s_symb);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_tr_s_symb
ON trade_request (tr_s_symb);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_t_st_id
ON trade (t_st_id);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_t_ca_id
ON trade (t_ca_id);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_t_s_symb
ON trade (t_s_symb);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_co_name
ON company (co_name);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_security
ON security (s_co_id, s_issue);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_holding
ON holding (h_ca_id, h_s_symb);
"

mysql -u root -D ${DBT5NAME} -e "
CREATE INDEX i_hh_t_id
ON holding_history (hh_t_id);
"

exit 0
