#!/bin/sh

#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2005-2010 Mark Wong & Open Source Development Labs, Inc.
#

usage()
{
	echo "Usage:"
	echo "    $0 [option]"
	echo "    $0 -h"
	echo "Options:"
	echo "    -b <integer>"
	echo "        Beginning customer ordinal position"
	echo "    -c <integer>"
	echo "        Number of customers for this instance"
	echo "    -h"
	echo "        this help"
	echo "    -i <path>"
	echo "        Path to EGen"
	echo "    -s <scale factor>"
	echo "        Scale factor (customers per 1 trtps)"
	echo "    -t <integer>"
	echo "        Number of customers (total)"
	echo "    -w <days>"
	echo "        Initial trade days (business days) to populate" 
}

REBUILD_DB=0

# These are minimum values defined by the specification.
CUSTOMERS_INSTANCE=5000
CUSTOMERS_TOTAL=5000
SCALE_FACTOR=500
STARTING_CUSTOMER_ID=1
ITD=300

while getopts "b:c:hi:l:p:s:t:w:" OPT; do
	case ${OPT} in
	b)
		STARTING_CUSTOMER_ID=${OPTARG}
		;;
	c)
		CUSTOMERS_INSTANCE=${OPTARG}
		;;
	i)
		EGENDIR=${OPTARG}
		;;
	h)
		usage
		exit 0
		;;
	s)
		SCALE_FACTOR=${OPTARG}
		;;
	t)
		CUSTOMERS_TOTAL=${OPTARG}
		;;
	w)
		ITD=${OPTARG}
		;;
	esac
done

if [ $# -eq 0 ]; then
	usage
	exit 1
fi

if [ "x${EGENDIR}" = "x" ]; then
	echo "EGENDIR not defined, specify EGen's directory."
	exit 1
else
	EGENLOADER="${EGENDIR}/bin/EGenLoader"
	if [ ! -f ${EGENLOADER} ]; then
		echo "Cannot verify that '${EGENLOADER}' exists..."
		exit 1
	fi
fi

dbt5-mysql-create-db || exit 1

# FIXME: Find a way to pass arguments to psql using EGen's -p flag, which
# apparently doesn't like arguments to have dashes (-) in them.
dbt5-mysql-create-tables || exit 1

(cd ${EGENDIR} && \
		${EGENLOADER} -b ${STARTING_CUSTOMER_ID} -l CUSTOM -f ${SCALE_FACTOR} \
		-w ${ITD} -c ${CUSTOMERS_INSTANCE} -t ${CUSTOMERS_TOTAL}) || exit 1
